### ISSUE TITLE
Steam Guard

### ISSUE THREAD

**Issue by kevjaN89** [joedwards32/CS2#1]
Hello,

can you add an env for SteamGuard Key? 

This computer has not been authenticated for your account using Steam Guard.
Please check your email for the message from Steam, and enter the Steam Guard
 code from that message.
You can also enter this code at any time using 'set_steam_guard_code'
 at the console.

**Comment by imanolpg** [comment]
I have the same problem. I can launch the image but there is no way to input the SteamGuard code. The `set_steam_guard_code` command is not found and there should be a delay time to enter the code before trying to authenticate

**Comment by joedwards32** [comment]
Hey,

Thanks for the feedback. I'll take a look at this later today.

@imanolpg, I designed the container for non-interactive use (e.g. under Fargate or k8s) so I'll need to think about adding an optional flag for interactive mode.

**Comment by imanolpg** [comment]
> Hey,
> 
> Thanks for the feedback. I'll take a look at this later today.
> 
> @imanolpg, I designed the container for non-interactive use (e.g. under Fargate or k8s) so I'll need to think about adding an optional flag for interactive mode.

Adding the interactive mode flag is a good Idea. I have seen you are using steamCmd, so you could interact with that terminal and input manually the username, password and the steamGuard code. This way you could also update the server app

**Comment by joedwards32** [comment]
@kevjaN89 I've added support for STEAMGUARD key as an environment variable.
@imanolpg I've spun out #4 for interactive support.
