### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by avoidik** [joedwards32/CS2#104]
hello,

after spending hours downloading steam server components I have faced the following issue:

```
Success! App '730' fully installed.
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
cp: cannot create regular file '/home/steam/cs2-dedicated/pre.sh': Permission denied
cp: cannot create regular file '/home/steam/cs2-dedicated/post.sh': Permission denied
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 71: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
bash: /home/steam/cs2-dedicated/pre.sh: No such file or directory
Starting CS2 Dedicated Server
entry.sh: line 104: ./cs2: No such file or directory
bash: /home/steam/cs2-dedicated/post.sh: No such file or directory
```

what could be the reason of it? would it be possible to check these files and permissions before wasting time on downloading?

**Comment by CM2Walki** [comment]
Could you drop your `docker run` command in here, please?

**Comment by avoidik** [comment]
I shouldn't have executed it under root account, in best case we should be using a user with id 1000 on a host machine, so that the bind-mount would correctly map users between container and host, that's my bad, apologies
