### ISSUE TITLE
Помогите пожалуйста

### ISSUE THREAD

**Issue by VaskaGROM** [joedwards32/CS2#110]
Возникла проблема на птеродактеле система debian Помогите пожалуйста
Пытался запустить сервер кс 2.
![2024-04-12_21-43-38](https://github.com/joedwards32/CS2/assets/146581600/b3921204-4f60-470c-89b3-13cd4a4ef42a)

**Comment by VaskaGROM** [comment]
pdate state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '740' state is 0x202 after update job.
ИЛИ вот

**Comment by joedwards32** [comment]
Hi, please make sure that you have provided sufficent storage space to the container (40GB) and that this is writable by the container.

Try `chmod 0777` on your volume directore if you are having trouble with the permissions

--- GOOGLE TRANSLATE ---

Привет, пожалуйста, убедитесь, что вы предоставили контейнеру достаточно места для хранения (40 ГБ) и что контейнер доступен для записи.

Попробуйте `chmod 0777` в каталоге вашего тома, если у вас проблемы с разрешениями.

**Comment by VaskaGROM** [comment]
Спасибо помогло только появилась другая проблема 
container@nookure~  Server marked as running...
Assigned persistent gameserver Steam ID [G:1:11313382].
Gameserver logged on to Steam, assigned identity steamid:85568392931352806
Set SteamNetworkingSockets P2P_STUN_ServerList to '162.254.198.46:3478' as per SteamNetworkingSocketsSerialized
VAC secure mode disabled.
GC Connection established for server version 1575, instance idx 1
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
Я уже 3 раза перезагружал все та же ошибка. Не понимаю зачем ему обновления он же только что установил кс.

**Comment by joedwards32** [comment]
Try forcing revalidation of the game files: https://github.com/joedwards32/CS2?tab=readme-ov-file#validating-game-files

`STEAMAPPVALIDATE=1`

--- GOOGLE TRANSLATE ---

Попробуйте принудительно выполнить повторную проверку файлов игры: https://github.com/joedwards32/CS2?tab=readme-ov-file#validating-game-files.

`STEAMAPPPVALIDATE=1`

**Comment by VaskaGROM** [comment]
Простите, я не очень понял куда надо вставлять STEAMAPPVALIDATE=1

**Comment by joedwards32** [comment]
You need to set it as one of the environment variables passed into the container at start up.

--- GOOGLE TRANSLATE ---

Вам необходимо установить его как одну из переменных среды, передаваемых в контейнер при запуске.

**Comment by VaskaGROM** [comment]
Не помогло 
 Public IP is 90.156.216.227.
Assigned persistent gameserver Steam ID [G:1:11313382].
Gameserver logged on to Steam, assigned identity steamid:85568392931352806
Set SteamNetworkingSockets P2P_STUN_ServerList to '155.133.252.54:3478' as per SteamNetworkingSocketsSerialized
VAC secure mode disabled.
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
GC Connection established for server version 1575, instance idx 1
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.

**Comment by joedwards32** [comment]
You definitely have an out of date server version. When I launch a fresh container I get:

`GC Connection established for server version 2000258, instance idx 1`

I recommend you delete the persistent data for that container and start again from a clean position.

If that doesn't work, perhaps Valve are applying some restrictions to Russian IPs/users?

--- GOOGLE TRANSLATE ---

У вас явно устаревшая версия сервера. Когда я запускаю новый контейнер, я получаю:

`GC Connection established for server version 2000258, instance idx 1`

Я рекомендую вам удалить постоянные данные для этого контейнера и начать заново с чистой позиции.

Если это не сработает, возможно, Valve применяет какие-то ограничения к российским IP/пользователям?

**Comment by VaskaGROM** [comment]
Вы запускали сервер на своём пк?

**Comment by joedwards32** [comment]
Yes, I get a much newer server version:

`GC Connection established for server version 2000258, instance idx 1`

--- GOOGLE TRANSLATE ---

Да, я получаю гораздо более новую версию сервера:

`GC Connection established for server version 2000258, instance idx 1`

**Comment by VaskaGROM** [comment]
Здравствуйте, спасибо что помогли я переустановил egg на птеродактель (скачал новее) всё заработало!

**Comment by joedwards32** [comment]
Ура!
