### ISSUE TITLE
server public ip attach problem

### ISSUE THREAD

**Issue by csoyuncu** [joedwards32/CS2#126]
Been a server admin since early 2000s (started CS in 1999) and, for whatever reason, the CS2 binary binds to [0.0.0.0](http://0.0.0.0/) on UDP instead of the specific -ip address specified in launch options. This worked with CS 1.6 but does not work in CS2. 

udp 0 0 0.0.0.0:27015 0.0.0.0:* 1156703/./cs2

how can i fix this problem?

**Comment by CM2Walki** [comment]
If you aren't using host network mode (`--net=host`). Then you can pass the IP to the publish parameter `-p`:

> If you don't specify an IP address (i.e., -p 80:80 instead of -p 127.0.0.1:80:80) when publishing a container's ports, Docker publishes the port on all interfaces (address 0.0.0.0) by default.

[Source](https://docs.docker.com/reference/cli/docker/container/run/#publish)

This will have the same result as using the start parameter on the binary.
