### ISSUE TITLE
Unable to make Metamod work

### ISSUE THREAD

**Issue by alperkaganavci** [joedwards32/CS2#131]
Hi everyone. I've setup a CS2 server with LinuxGSM before and I was able to install Metamod and other addons with no issues, however, unable to make Metamod work at the moment.

There is only one csgo folder and I am perfectly sure that I am adding the `Game    csgo/addons/metamod` to the correct place. I will copy paste the part where we suppose to edit below so that you can see as well. I have downloaded the latest version of Metamod that has been released after the latest big update (Build 1314 from 2.0 Branch). It just doesn't work. Anyone facing the same problem or am I missing something please?

```
LayeredOnMod	csgo_imported
	SatelliteDir	csgo_gc

	FileSystem
	{
		SearchPaths
		{
			Game_LowViolence	csgo_lv // Perfect World content override

			Game    csgo/addons/metamod
			Game	csgo
			Game	csgo_imported
			Game	csgo_core
			Game	core

			Mod		csgo
			Mod		csgo_imported
			Mod		csgo_core

			AddonRoot			csgo_addons

			LayeredGameRoot		"../game_otherplatforms/etc" [$MOBILE || $ETC_TEXTURES] //Some platforms do not support DXT compression. ETC is a well-supported alternative.
			LayeredGameRoot		"../game_otherplatforms/low_bitrate" [$MOBILE]
		}

		"UserSettingsPathID"	"USRLOCAL"
		"UserSettingsFileEx"	"cs2_"
	}

	Engine2
	{
		"DepotBuildDateTimeInTitleBar" "1"
		"InitFilterTextEarly" "1"
		"CNPW"	"numbers"
		"LvConfig"	"0"
	} 
```

**Comment by M-archand** [comment]
Metamod 1314 is working fine for me with this docker image. It could be possible that something is corrupted in your persistent files. I was having issues last month with this docker image so I backed up my addons+cfg folder and deleted my volume and reinstalled and everything worked fine after that, so my suggestion would be to try that perhaps.
