### ISSUE TITLE
No password is asked for on client connet resulting in 'Badpassword' error

### ISSUE THREAD

**Issue by CharlieCoops7** [joedwards32/CS2#136]
If I add a password (even a simple 3 letter password) to the docker compose file, the server always returns a 'badpassword' when trying to connect (it doesn't even prompt the client for a password).

In the Steam Server Browser, the server is advertised as not needing a password which is why the game client trys to connect without a password. Removing the server password, allows connection to the server.

Let me know any info I should share to help anyone troubleshoot.

**Comment by joedwards32** [comment]
Can you share your docker compose file, with your steam token redacted?

**Comment by Yukics** [comment]
connect server:port; password changeme

**Comment by CharlieCoops7** [comment]
Thanks Yukics but The readme says to follow this format below so I don't think it's that:
CS2_PW="changeme"           (CS2 server password)

**Comment by joedwards32** [comment]
`connect server:port; password abc` should work given your config, can you confirm?

I'll check how a fresh deployment works with the server browser.

**Comment by joedwards32** [comment]
Similar behavior reported elsewhere: https://steamcommunity.com/discussions/forum/14/7119694909423654798/

**Comment by joedwards32** [comment]
Closing this issue, but feel free to reopen @CharlieCoops7 if you still think there is a bug here for this project to fix.
