### ISSUE TITLE
CS2_BOT_QUOTA shadows CS2_BOT_QUOTA_MODE

### ISSUE THREAD

**Issue by daiser** [joedwards32/CS2#137]
Hi!

`sed` in entry.sh replaces all `bot_quota_mode` with `bot_quota $CS2_BOT_QUOTA`.

I believe it could be fixed by changing regex here: https://github.com/joedwards32/CS2/blob/7de1841926f8da5e4263d90c1333b56f1ecb0fde/bookworm/etc/entry.sh#L64

Possible fix `"s/bot_quota .*/bot_quota ${CS2_BOT_QUOTA}/"`. Note space between `bot_quota` and `.*`.

Another option is `"s/bot_quota [0-9]*/bot_quota ${CS2_BOT_QUOTA}/"`.

**Comment by joedwards32** [comment]
Thanks for the bug report. I'll take a look when I have a mo.
