### ISSUE TITLE
Connection to server not possible - wrong password

### ISSUE THREAD

**Issue by sbergt** [joedwards32/CS2#14]
Hi there,

I setup the server with the standard login password "changeme". I found my server on CS2, but if I want to connect the server says incorrect password. Also no password prompt is show up and it seems like the server is not password locked. Any idea to solve this?

**Comment by esdete2** [comment]
I have the same problem. It seems that the client does not get the information that the server is protected (no lock icon) and then fails when connecting without password. A simple workaround for now is to connect via console command:

`connect 123.123.123.123:27015; password yourpassword`

**Comment by joedwards32** [comment]
As @esdete2 says, the server is correctly requiring a password.

The rest of the reported behaviour is CS2 bugs I think. There [isn't proper support for community servers yet](https://dotesports.com/counter-strike/news/how-to-fix-cs2-community-servers-not-working), hopefully Valve will patch in better support soon.

For now you are best off using the `connect` console command.
