### ISSUE TITLE
Issues with server updating

### ISSUE THREAD

**Issue by magnushirst** [joedwards32/CS2#20]
Anyone having issues with the server not updating after the recent CS2 update? Have tried restarting and stop/starting the container but when I follow the logs, I don't see any attempt to update and the server just starts as normal. When clients connect, they get an out of date client error.

**Comment by joedwards32** [comment]
Thanks for the issue report.

I just fired up the container in my build environment, where I use a volume for game files persistence testing:

```
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 10.05 (262442482 / 2610392123)
 Update state (0x61) downloading, progress: 31.27 (816394506 / 2610392123)
 Update state (0x61) downloading, progress: 41.18 (1075064063 / 2610392123)
```

Can connect with the latest client

![Screenshot from 2023-10-11 10-46-39](https://github.com/joedwards32/CS2/assets/23718906/6c24623b-e670-4ee8-ac53-454f5c5d3c59)

**Comment by jonisj** [comment]
You might get issues with auto update, if your STEAMGUARD token is old. Try getting a fresh code and then launching your server.

**Comment by ThatFave** [comment]
As a workaround to steamguard, I created a new steam account since you do not need to own cs2 to do this, and have steamguard disabled (use with caution and a secure password of course).

**Comment by joedwards32** [comment]
> As a workaround to steamguard, I created a new steam account since you do not need to own cs2 to do this, and have steamguard disabled (use with caution and a secure password of course).

This is my approach too. Best not to use your personal account IMO.

Hopefully Valve will allow anonymous downloading of CS2 at some point :crossed_fingers:

**Comment by magnushirst** [comment]
Really strange that it's still not updating for me then. I don't have steam guard on this account so I used email 2FA which is different but I wouldn't think is an important difference.

```
SRedirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...OK
```

I'm running this on my Unraid server with the following config:
```
docker run  
  -d  
  --name='cs2'  
  --net='host'  
  -e TZ="Europe/London"  
  -e HOST_OS="Unraid"  
  -e HOST_HOSTNAME="Tower"  
  -e HOST_CONTAINERNAME="cs2"  
  -e 'STEAMUSER'='mangochutneycs2'  
  -e 'STEAMPASS'='XXXXXXXXXXXXXX'  
  -e 'CS2_SERVERNAME'='SCRUB_CITY'  
  -e 'CS2_PORT'='27015'  
  -e 'UDP_PORT_27015'='27015'  
  -e 'CS2_RCONPW'='XXXXXXX'  
  -e 'CS2_PW'='XXXXXX'  
  -e 'CS2_BOT_QUOTA'='0'  
  -e 'STEAMGUARD'='XXXX'  
  -e 'CS2_ADDITIONAL_ARGS'='+ip 0.0.0.0 +net_public_adr 81.XXX.XXX.XXX'  
  -e 'CS2_MAPGROUP'='mg_active'  
  -l net.unraid.docker.managed=dockerman  
  -v '/mnt/user/appdata/cs2':'/home/steam/cs2-dedicated/':'rw'
  'joedwards32/cs2'  
```

My only other idea is to wipe the container and let it start from scratch.

**Comment by magnushirst** [comment]
Resolved with issue with steam guard not being correct, not updating but starting the server anyway
