### ISSUE TITLE
Error! App '730' state is 0x202 after update job.

### ISSUE THREAD

**Issue by morkvk** [joedwards32/CS2#23]
please help 

[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'readysurtin' to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
roaming config store loaded successfully - 1826 bytes.
migrating temporary roaming config store
src/clientdll/internalcallbacks.cpp (115) : Re-entering DispatchCallback, this is dangerous.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x11) preallocating, progress: 1.83 (667536162 / 36388770634)
Error! App '730' state is 0x202 after update job.
Updating Workshop items for App '730'.
 Update state (0x0) : Timed out waiting for update to start, bailing.
Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 11 items discarded.
src/clientdll/contentupdatecontext.cpp (752) : m_uIOCurrentCacheSize == 0
src/clientdll/contentupdatecontext.cpp (752) : m_uIOCurrentCacheSize == 0
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 3 items discarded.
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 35: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
entry.sh: line 49: ./cs2: No such file or directory

**Comment by magnushirst** [comment]
Just a guess, but I wonder if this is a permissions type problem with:
```
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 35: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
entry.sh: line 49: ./cs2: No such file or directory
```
You could double check that by exec'ing on the container and seeing if you can create files in ` /home/steam/cs2-dedicated/game/csgo/cfg/`

**Comment by jedwards-jagex** [comment]
As @magnushirst says, check the permissions.

If you are using a persistent volume then make sure that it is writable.

**Comment by joedwards32** [comment]
As @magnushirst says, check the permissions.

If you are using a persistent volume make sure that it is writeable.

**Comment by joedwards32** [comment]
It depends on what user id your container executes under.

Setting permissions on the directory you are mounting as `0777` should work for testing.

**Comment by joedwards32** [comment]
Also, if you are running the container under a system where you need to define how much disk space is available (like Fargate) then there needs to be at least 40GB.

**Comment by morkvk** [comment]
I did great, but I don't understand how to log in to the console

![image](https://github.com/joedwards32/CS2/assets/140403549/dbc1a8d7-87d0-4a9a-984d-62031b6370bc)

**Comment by bgdnsc** [comment]
@morkvk logging in to the console -- that's something to do with how to use Portainer's features
Check out [this documentation](https://docs.portainer.io/user/docker/containers/console)

**Comment by morkvk** [comment]
I tried using the command but I can't interact with the console
docker container attach cs2-dedicated

**Comment by joedwards32** [comment]
@morkvk I'm glad you got your container started :)

For Portainer specific questions you are better off directing them to Portainer support or the community like https://www.reddit.com/r/portainer/

**Comment by joedwards32** [comment]
Closing this issue as the problems are now around Portainer features/usage.
