### ISSUE TITLE
Server not starting up, process getting terminated

### ISSUE THREAD

**Issue by bageshwar** [joedwards32/CS2#25]
Hi, 

First of all, thanks for taking the time to package this into a container for easy setup.

When I try to run the container, it crashes. Sharing the last few lines of the log

```
Unknown command 'mp_molotovusedelay'!
Unknown command 'spec_freeze_panel_extended_time'!
Unknown command 'sv_occlude_players'!
Unknown command 'occlusion_test_async'!
Unknown command 'sv_gameinstructor_enable'!
Waited 50.5ms for SteamNetworkingSockets lock [ServiceThread]
src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp(2141): SteamnetworkingSockets service thread waited 1151ms for lock!  This directly adds to network latency!  It could be a bug, but it's usually caused by general performance problem such as thread starvation or a debug output handler taking too long.
entry.sh: line 49:    31 Killed                  ./cs2 -dedicated -port 27015 -console -usercon -maxplayers_override 10 +game_type 0 +game_mode 1 +mapgroup mg_active +map de_inferno +rcon_password changeme +sv_password changeme
```

I guess it has something to do with `service thread waited 1151ms for lock`, but I am unsure how to resolve it. Any suggestions here?

**Comment by joedwards32** [comment]
Hi @bageshwar, can you share the command you are using to launch the container (be sure not to share your steam user/password)?

**Comment by bageshwar** [comment]
Hi @joedwards32 , 

This issue was low memory, and the container was crashing because of it. The host VM had 500 MB free memory, which used to be enough to run csgo ds, but running cs2 ds via docker takes approx 1.1g of memory.  The issue was resolved after I resized my VM. I will raise a PR on the README highlighting this, so this might help others

**Comment by joedwards32** [comment]
Thanks for the update. I look forward to your PR :)
