### ISSUE TITLE
Container Exited (127)

### ISSUE THREAD

**Issue by dmbokhan** [joedwards32/CS2#28]
Docker container status is "Exited (127)" just after I execute docker run command.

`~# docker ps --all
CONTAINER ID   IMAGE             COMMAND           CREATED          STATUS                       PORTS     NAMES
622546b1fecf   joedwards32/cs2   "bash entry.sh"   7 seconds ago    Exited (127) 4 seconds ago             cs2`

How to troubleshoot the issue?

**Comment by joedwards32** [comment]
Hi @dmbokhan,

Can you share the output of `docker logs 622546b1fecf`?

**Comment by dmbokhan** [comment]
Hi @joedwards32,

`~# docker logs 622546b1fecf
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[----] Verifying installation...
[  0%] Downloading update...
[  0%] !!! Fatal Error: Steamcmd needs 250MB of free disk space to update.
src/tier0/threadtools.cpp (3690) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x5823f660/0x0xf7724b'
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 35: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
entry.sh: line 49: ./cs2: No such file or directory`


`~# vmstat 
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 3434380  17280 418960    0    0    83     4   17   24  0  0 99  0  0`

**Comment by joedwards32** [comment]
There's not enough disk space available to the container.

Are you attaching a persistent volume?

**Comment by joedwards32** [comment]
You need at least 32GB free to download all the CS2 files

**Comment by dmbokhan** [comment]
I'm trying to run the container from the first option from the first option of your README.

Thank you, I have no idea why I was thinking about RAM instead of disk space. I had uncontainered version of CS2 on the VM, so the disk was almost full.

But now I should enter the Steam Guard Code, how should I do that?

`# docker logs 4ebae2caab94
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'hedgehog165' to Steam Public...
This computer has not been authenticated for your account using Steam Guard.
Please check your email for the message from Steam, and enter the Steam Guard
 code from that message.
You can also enter this code at any time using 'set_steam_guard_code'
 at the console.
Steam Guard code:FAILED (Account Logon Denied)
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 35: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
entry.sh: line 49: ./cs2: No such file or directory`

**Comment by joedwards32** [comment]
You can take the latest steamguard code emailed to you by Valve and set it using `--env STEAMGUARD=$YOUR_CODE`.
