### ISSUE TITLE
Container Environment

### ISSUE THREAD

**Issue by kevjaN89** [joedwards32/CS2#3]
Hello Again :), 

unfortunately, the container environment is not working correctly either. RCON password and server password are not being taken over, as well as the number of players or CS2_MAXPLAYERS. I have already adjusted them multiple times, but the server always shows 64 slots. The RCON password and server password need to be passed into the server config. If possible, please also add an environment variable for the hostname :)

Kind Regards 
kevjaN

**Comment by joedwards32** [comment]
Hey @kevjaN89 :)

Thanks again for the feedback.

Server password is working for me, I must admit I haven't tested RCON though.

CS2_MAXPLAYERS bug confirmed, doesn't work for me either. Will look into all of the above after work.

**Comment by joedwards32** [comment]
CS2_MAXPLAYERS reports 64 in the server STDOUT but I am not able to connect more than the specified number, e.g. 10, players in practice. Possibly a CS2 bug?

Server Password is working for me. The only gotcha that may make it appear like it doesn't work is that CS2 remembers the password you used to connect to a server previously (based on IP/hostname) and offers it automagically.

RCON doesn't work for me at all though. Forget the Docker container, I cant get it to work on a regular Linux server.

Any suggestions on what the correct configuration is beyond `-usercon` and  `+rcon_password`? I've tried setting `rcon_password` in server.cfg too.

**Comment by joedwards32** [comment]
Actually, scratch that. RCON is working, just not in game. I can see other reports of similar online.

I can access RCON with the password using an alternative client, such as: https://github.com/forewing/csgo-rcon

**Comment by joedwards32** [comment]
@kevjaN89 I've pushed a new version of the Docker image. Fixes:

- Server name support added
- pw now written to server.cfg
- rcon_pw now written to server.cfg

I've validated that rcon works using an alternative client. Seems busted in CS2 proper right now.

I've validated that password is being set correctly.

CS2_MAXPLAYERS seems to have the desired effect (limiting the number of players), even though stdout reports a different value.

Please test and let me know how you get on :)

**Comment by kevjaN89** [comment]
@joedwards32 
- Server name env working fine
- Server pw env working fine
- rcon_pw env working fine
- max players env is still being ignored; I think there's still a bug. 
 Server Log: SV:  64 player server started

But already, thank you very much for everything else :)

Kind regards
kevjaN89
