### ISSUE TITLE
How to provide custom configuration files (e.g., server.cfg) to the CS2 server process?

### ISSUE THREAD

**Issue by miguno** [joedwards32/CS2#48]
Background:
I have a custom `server.cfg` plus a customized `gamemode_competitive_server.cfg` for my non-Docker based dedicated servers.  These configs define additional settings that go beyond what I can override with this project's ENV variables for Docker.

Questions:

1. What is the best way to pass custom config files (such as `server.cfg` et al. above) to the dockerized CS2 server process with this project?  (I think it is not a good idea to add further overrides for all the possible server-side settings that one could possible need, so passing the full file seems like a better approach.)
2. I have seen there's `CS2_ADDITIONAL_ARGS`, where one can pass in something like `+exec my.cfg`. Would this be a workable approach? I am asking because CS2 has a specific priority order in which files and their settings are being parsed and applied/overriden.
3. If `CS2_ADDITIONAL_ARGS` is indeed a good approach, how do (a) the ENV variables and their (default or overridden) settings interplay with (b) config files passed via `CS_ADDITIONAL_FLAGS`? Which of the two take precedence?

**Comment by joedwards32** [comment]
Hi @miguno,

I haven't played much with heavily customising the configs yet so I don't have a preferred solution to offer.

Responses to your questions:

1. `server.cfg` is special. This container image overwrites it with https://github.com/joedwards32/CS2/blob/main/bullseye/etc/server.cfg (templated from ENV inputs). I agree more overrides are not the way to go (too many).
2. `+exec my.cfg` will execute the specified config file but I haven't experimented with what this does to the load order of config files
3. I haven't tested to validate, but I think `server.cfg` will still be loaded before the specified `+exec` file. Order would be something like: 
```
execing server_default.cfg
execing server.cfg
execing gamemode_competitive.cfg
execing gamemode_competitive_server.cfg
execing my.cfg
```

The approach I propose you test (I'm interested to see what you learn!) is:

- Leave `server.cfg` alone. Customise it using the environment variables provided (we can add a few more if needed).
- Add your own `gamemode_competitive_server.cfg` to the `cfg` folder with all additional customisations. You don't need `+exec` for this, the CS2 server already tried to load it but it isn't present by default.

See this log snippet:

```
execing server_default.cfg
execing server.cfg
execing gamemode_competitive.cfg
exec: couldn't exec '{*}cfg/gamemode_competitive_server.cfg', unable to read file
```

**Comment by miguno** [comment]
I noticed https://github.com/joedwards32/CS2/commit/47b89294f18db10db3a362a7653939609f28c58c.

Would it be an option to update the code such that, given a mounted persistent volume, that any available `gamemode_*_server.cfg` files existing in that volume be copied into `/etc/` in the container, alongside `server.cfg` and the pre/post scripts?

**Comment by joedwards32** [comment]
@miguno I recently added support for supplying a bundle of custom configs from a URL. See https://github.com/joedwards32/CS2#customisation-bundle.

The example bundle committed to the repo shows the use case of overriding Competitive mode defaults via `gamemode_competitive_server.cfg`.

**Comment by miguno** [comment]
Will take a look, thank you @joedwards32 !
