### ISSUE TITLE
Metamod, gameinfo.gi, and pre-hooks

### ISSUE THREAD

**Issue by domyd** [joedwards32/CS2#53]
Hello! I've been trying to setup a CS2 server with Metamod. However, Metamod requires an edit to the `game/csgo/gameinfo.gi` file, which is always overwritten after a game update. I would like a way to edit that file automatically just before `cs2` is launched, by executing something like this script: https://github.com/ghostcap-gaming/cs2-metamod-re-enable-script

You've mentioned pre-hooks in #18, which seems like a nice solution to this.

Are there perhaps other ways I can achieve this that I'm missing?

Thank you for this image :)

**Comment by joedwards32** [comment]
Hey @domyd, do the changes in #55 fit your needs?

**Comment by domyd** [comment]
Yeah, that looks like it'll work. Thanks for the quick response!
