### ISSUE TITLE
Environment Variable CS2_PORT never used

### ISSUE THREAD

**Issue by galinette-34** [joedwards32/CS2#6]
The environment variable `CS2_PORT` should be used in script `entry.sh`. 

```
"${STEAMAPPDIR}/game/bin/linuxsteamrt64/cs2" -dedicated -port "${CS2_PORT}" \
...
```

Worked for me after setting `CS2_PORT` to another port number.

**Comment by jedwards-jagex** [comment]
Good spot! Will get that fixed now.

**Comment by joedwards32** [comment]
Good spot! Will get that fixed now.

**Comment by joedwards32** [comment]
Thanks for the feed back, @galinette-34. New version has been pushed to Docker Hub.
