### ISSUE TITLE
Add libicu, icu-libs, libicu-dev

### ISSUE THREAD

**Issue by creazy231** [joedwards32/CS2#61]
Want to add some mods to my server but `CounterStrikeSharp ` ( https://docs.cssharp.dev/guides/getting-started/ ) says _Depending on the os you might also either need to install libicu / icu-libs / libicu-dev using your package manager for .NET to run_

**Comment by Hackmastr** [comment]
You don't need to install anything else, just setup a variable like so:
```
...
   container_name: cs2-dedicated
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
...
```

**Comment by creazy231** [comment]
works perfectly <3
