### ISSUE TITLE
Doesn't work on Apple M1 chip

### ISSUE THREAD

**Issue by kus** [joedwards32/CS2#63]
I know it's not your repo, but just curious if you know anyone who has successfully gotten this to run on an Apple M1 chip?

Steamcmd behaves very weirdly. You first get this error `Unable to determine CPU Frequency. Try defining CPU_MHZ.` so I define the environment variable with `--env CPU_MHZ=2500` then that error goes away, but it won't actually download a game.

You get lots of errors like this `src/common/processpipe_posix.cpp (279) : invalid name/address:port string provided to BSetIpPortFromName SteamClientService_25`

I launch docker with this command:

`docker run --env CPU_MHZ=2500 -p 27015:27015 --platform linux/amd64 joedwards32/cs2`

I've tried setting up a bare bones docker image running Ubuntu and Steamcmd and can't get it to work either, but the same bash script works on Google Cloud on a Ubuntu VM.

Any ideas of anything I should try?

**Comment by yannickvr** [comment]
AFAIK M1 chips are ARM architecture and CS requires X86 architecture. I think there are ways for running things in x86 mode on M1, slow as hell, but it might fix it for you.

**Comment by joedwards32** [comment]
`--platform linux/amd64` tells Docker to use macOS' Rosetta x86_64 emulation when running the container. This isn't perfect and there will be bugs with some applications.

If you are set on running the container on your M1 device, you could try running a QEMU VM and hope that the QEMU x64_64 emulation is OK.

If you are prepared to use Google Cloud or AWS then I recommend running the container under one of their serverless containerisation services. E.g. AWS Fargate.

Marking this issue as closed as CS2 M1 support isn't within the scope of this project.

Gd luck :)
