### ISSUE TITLE
Server password configured  but I have problems

### ISSUE THREAD

**Issue by mw-kiss** [joedwards32/CS2#67]
Hello,

First of all thank you for your work.
I found you docker easy to use and easy to launch, my goal was to deploy a cs2 server in order to practice stuff ingame with a friend.
AFAIK its not possible to do it ingame without a dedicated server.

As I am not used to do things with docker I had trouble but everythings seems to work now.
I copy/paste every env vars in a env.list file which is taken into account by my launch command:

docker run -d --name=cs2 --env-file ./env.list -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2

I don't have experience with docker so I am now using only:

docker run - kill - rm - ps and logs +cs2 to manage the server.

Nothing mentioned the game token so I add it via CS2_ADDITIONAL_ARGS=""   and It seems to work since I don't have the message missing token, lan only...

I just saw your update 66 which include the token into another var.

My problem is that I can't connect to my server because it says "incorrect password" at the connection.
My server password is set by the env var : 
CS2_PW="pcw1"

All env vars seems to work since I can scan the server in steam "server browsing" (but it show no password in this GUI when server is listed)

In game : connect myserverip return bad password

connect  myserverip pw1 return bad password

Fun fact, as I said before the server browser show my server without password and the connect option launch my game and try to connect but => bad password 

Do you have any idea ?
Tonight I will try to reboot the server maybe with a password without number, or without password....

I know github issue is to report bugs and you code seems good its probably a steam bug ?

Is it possible to enter interactive with and maybe type sv_password to be sure about what is set up ? I mean enter interactive with what I see by : docker logs cs2 ?

Thank you

**Comment by joedwards32** [comment]
The `connect` syntax is:

`connect myserverip; password pcw1`

**Comment by mw-kiss** [comment]
Changed the password to toto and tried:
connect myserverip; password pcw1 game : server rejected bad password.

Is there a way to enter interactive mode here:

![image](https://github.com/joedwards32/CS2/assets/6216106/4e5389f9-89ba-4219-bee7-fc56b0e927cf)
 its the resultat of my docker logs cs2, to type sv_password xxx

I don't understand.

Here is my env.list file which seems to work, good server name good maxplayer ...

CS2_SERVERNAME="Private Server"
CS2_IP=""
CS2_PORT=27015
CS2_RCON_PORT=""
CS2_LAN="0"
CS2_RCONPW="rconpw1"
CS2_PW="pcw1"
CS2_MAXPLAYERS=12
CS2_ADDITIONAL_ARGS="+sv_setsteamaccount 0552XXXXXXXXXXXXXXXXX"
CS2_GAMEALIAS=""
CS2_GAMETYPE=0
CS2_GAMEMODE=1
CS2_MAPGROUP="mg_active"
CS2_STARTMAP="de_inferno"
CS2_BOT_DIFFICULTY=""
CS2_BOT_QUOTA="0"
CS2_BOT_QUOTA_MODE=""
TV_ENABLE=0
TV_PORT=27020
TV_AUTORECORD=0
TV_PW="changeme"
TV_RELAY_PW="changeme"
TV_MAXRATE=0
TV_DELAY=0
