### ISSUE TITLE
How to run commands and change map for example?

### ISSUE THREAD

**Issue by LEMMIIX** [joedwards32/CS2#68]
Hello,
we managed to get the server up and running and were able to join it via the console with the IP and password. We tried to connect to the server via rcon to run server commands (e.g, change maps, change password) but we couldn't connect to the rcon client. This seems to be an rcon bug (?). We still want to change some settings while the server is running. Is there a possibility to access the server via the terminal on the docker container? 
Normally, you can run server commands when you start the server from the terminal but since the server is started automatically we don't have access to it. 
help.

**Comment by LEMMIIX** [comment]
hey thank you for you fast answer. So there is no possibility to run commands on the docker container?

**Comment by LEMMIIX** [comment]
I have already entered the docker container as you told like docker exec -it $your_container_id /bin/bash, but what i meant getting access to /game/bin/../cs2 (its running the server instance right?, normally you can run server commands after running this)

**Comment by joedwards32** [comment]
Gotcha. If you launch the container interactively then you will have access to the stdin/stdout of the running process.

`-i` to keep STDIN attached, allowing you to interact with the running process
`-t` to attach a tty to the container

Normally, the README directs you to use `-d` with backgrounds the container.

`docker run -it --name=cs2 -e SRCDS_TOKEN={YOURTOKEN} -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2`
