### ISSUE TITLE
Unable to set sv_cheats to true in CS2 Docker container

### ISSUE THREAD

**Issue by macosky** [joedwards32/CS2#70]
**Description:**
I am currently facing an issue with setting `sv_cheats` to true in the CS2 Docker container. Despite configuring it in the `custom.cfg` file and attempting to override it using a `pre.sh` script to modify `server.cfg`, the `sv_cheats` value remains unaffected.

**Setup:**
- Docker Compose version: 3
- Image: joedwards32/cs2
- Container Name: cs2
- Environment Variables:
  - SRCDS_TOKEN=XXX
  - CS2_SERVERNAME=XXX
  - CS2_PW=XXX
  - CS2_RCONPW=XXX
  - CS2_ADDITIONAL_ARGS="+exec custom.cfg"
- Volumes:
  - /path/to/docker_data/cs2/:/home/steam/cs2-dedicated/
- Ports:
  - "27015:27015/tcp"
  - "27015:27015/udp"
  - "27020:27020/tcp"

**Additional Information:**
- The content of `custom.cfg` file:
  ```
  sv_cheats 1
  ```
  (I have also tried `sv_cheats true`)

- Attempted to override `server.cfg` using a `pre.sh` script, but the changes to `sv_cheats` do not take effect.

**Expected Behavior:**
The `sv_cheats` value should be set to true, either through the `custom.cfg` file or the `pre.sh` script, allowing cheats to be used in the CS2 server.

**Actual Behavior:**
Despite setting `sv_cheats` in the configuration files, cheats do not work in the CS2 server, indicating that `sv_cheats` is not being set to true.

**Environment:**
- Operating System server: Container PVE , Debian
- Docker Version: Docker version 24.0.2, build cb74dfc

Thank you for your assistance in resolving this issue.

**Comment by joedwards32** [comment]
Hey,

Can you share your `pre.sh` script?

I can potentially add a `sv_cheats` to https://github.com/joedwards32/CS2/blob/main/bullseye/etc/server.cfg.

**Comment by labaland** [comment]
I cant enable cheat. How do i do it? I have CS2_CHEATS=1 in my docker-compose file
sv_cheat 1 wont work

**Comment by joedwards32** [comment]
@labaland Please make sure you have pulled the latest version of the docker image.

**Comment by labaland** [comment]
> @labaland Please make sure you have pulled the latest version of the docker image.

Hi! Yes, i use this image: joedwards32/cs2:latest

**Comment by labaland** [comment]
And how do i exec a cfg? rcon exec name, does nothing. 
And i dont have to use rcon when adding or kicking bots for example

**Comment by macosky** [comment]
Hi everyone,

Sorry for the delayed response; I have been quite busy lately.

I managed to enable sv_cheats, BUT only using RCON after the server startup and authentication to the Valve server.

For simplicity, I am using this tool:
https://github.com/fpaezf/CS2-RCON-Tool-V2


This is not a fix but a way to overide the issue. 

I'm not sure why, but even after adding the line to the CFG file before starting, sv_cheats is not enabled. 
I'm uncertain whether it's a bug in your implementation or a '''''feature''''' of SteamCMD.

**Comment by joedwards32** [comment]
Interesting. This definitely worked when I first implemented it. I'll test again with the latest CS2 build.

**Comment by joedwards32** [comment]
When I set `CS2_CHEATS=1` cheats show as enabled in rcon

```
$ ./csgo-rcon-v1.3.0-linux-amd64 -a 192.168.0.31:27015 -p ******* sv_cheats
sv_cheats = true
```
