### ISSUE TITLE
How validate files and download deleted files?

### ISSUE THREAD

**Issue by janpepu** [joedwards32/CS2#71]
Hi,
Thanks for your  container.

I have a question , how validate files of the server if i delete one (gameinfo.gi )?
I have create a directory mount to /home/steam/cs2-dedicated
https://developer.valvesoftware.com/wiki/Gameinfo.gi is not the last version.

Thanks

**Comment by joedwards32** [comment]
@janpepu See #91

`STEAMAPPVALIDATE=1`

**Comment by janpepu** [comment]
thanks
