### ISSUE TITLE
Examples on how to edit start up script!

### ISSUE THREAD

**Issue by labaland** [joedwards32/CS2#80]
Can someone show me how to modify the start up script? How i add the commands. I dont know.
And i also want to host my workshop collection, but i dont know how to do that also :'D

**Comment by labaland** [comment]
None?

**Comment by labaland** [comment]
@joedwards32 Can u please give a example? :)

**Comment by joedwards32** [comment]
Hi @labaland,

There is an example in https://github.com/joedwards32/CS2/blob/main/examples/cs2.cfg.tgz

What you need to do is construct a Tar GZip like that one, containing your scripts.

Host that TGZ somewhere and use CS2_CFG_URL to download it.

Alternatively, you can bind mount in a specific script file:

```
-v ./pre.sh:/etc/pre.sh
```
